#!/bin/bash
latex interpretable_ml.tex
bibtex interpretable_ml
latex interpretable_ml.tex
latex interpretable_ml.tex
pdflatex interpretable_ml.tex
rm interpretable_ml.pdf
pdflatex interpretable_ml.tex
rm *.aux
rm *.bbl
rm *.blg
rm *.dvi
rm *.log
rm *.nav
rm *.out
rm *.run.xml
rm *.snm
rm *.toc
rm interpretable_ml-blx.bib
